export const user = [
  {
    id: '1',
    fullName: 'Kunnikar Boonbunlu',
    username: 'Kunnikar',
    profileImg: '/avatars/girl2.png',
    tweets: [
      {
        id: '1',
        text: 'How you guys doing? 😊',
        likes: 5,
      },
      {
        id: '2',
        text: 'Astronaut in a room of drawers, generated by Midjourney. 🚀',
        likes: 10,
      },
      {
        id: '3',
        text: "I'm learning GO this week. Any tips? 🤔",
        likes: 15,
      },
    ],
  },
  {
    id: '2',
    fullName: 'Thomas Falck',
    username: 'Thomas',
    profileImg: '/avatars/boy2.png',
    tweets: [
      {
        id: '1',
        text: 'How you guys doing? 😊',
        likes: 5,
      },
      {
        id: '2',
        text: 'Astronaut in a room of drawers, generated by Midjourney. 🚀',
        likes: 10,
      },
      {
        id: '3',
        text: "I'm learning GO this week. Any tips? 🤔",
        likes: 15,
      },
    ],
  },
];

export const POSTS = [
  {
    id: '1',
    text: "Let's build a fullstack WhatsApp clone with NEXT.JS 14 😍",
    img: '/posts/post1.png',
    user: {
      username: 'kunnikar',
      profileImg: '/avatars/boy1.png',
      fullName: 'Kunnikar Boonbunlu',
    },
    comments: [
      {
        _id: '1',
        text: 'Nice Tutorial',
        user: {
          username: 'mary',
          profileImg: '/avatars/girl1.png',
          fullName: 'Mary Lee',
        },
      },
    ],
    likes: ['6658s891', '6658s892', '6658s893', '6658s894'],
  },
  {
    id: '2',
    text: 'How you guys doing? 😊',
    user: {
      username: 'thomas',
      profileImg: '/avatars/boy2.png',
      fullName: 'Thomas Falck',
    },
    comments: [
      {
        _id: '1',
        text: 'Nice Tutorial',
        user: {
          username: 'mary',
          profileImg: '/avatars/girl2.png',
          fullName: 'Mary Lee',
        },
      },
    ],
    likes: ['6658s891', '6658s892', '6658s893', '6658s894'],
  },
  {
    id: '3',
    text: 'Astronaut in a room of drawers, generated by Midjourney. 🚀',
    img: '/posts/post2.png',
    user: {
      username: 'thomas',
      profileImg: '/avatars/boy3.png',
      fullName: 'Thomas Falck',
    },
    comments: [],
    likes: [
      '6658s891',
      '6658s892',
      '6658s893',
      '6658s894',
      '6658s895',
      '6658s896',
    ],
  },
  {
    id: '4',
    text: "I'm learning GO this week. Any tips? 🤔",
    img: '/posts/post3.png',
    user: {
      username: 'thomas',
      profileImg: '/avatars/boy3.png',
      fullName: 'Thomas Falck',
    },
    comments: [
      {
        id: '1',
        text: 'Nice Tutorial',
        user: {
          username: 'mary',
          profileImg: '/avatars/girl3.png',
          fullName: 'Mary Lee',
        },
      },
    ],
    likes: [
      '6658s891',
      '6658s892',
      '6658s893',
      '6658s894',
      '6658s895',
      '6658s896',
      '6658s897',
      '6658s898',
      '6658s899',
    ],
  },
];

export const USERS_FOR_RIGHT_PANEL = [
  {
    id: '1',
    fullName: 'Thomas Falck',
    username: 'thomas',
    profileImg: '/avatars/boy2.png',
  },
  {
    id: '2',
    fullName: 'Mary Lee',
    username: 'mary',
    profileImg: '/avatars/girl1.png',
  },
  {
    id: '3',
    fullName: 'Tom Hanks',
    username: 'tom',
    profileImg: '/avatars/boy3.png',
  },
  {
    id: '4',
    fullName: 'Daisy Rose',
    username: 'daisy',
    profileImg: '/avatars/girl2.png',
  },
];
